#!/bin/sh

# This file obtains the data needed for the overall import processing,
# creates a fresh database, and imports the data.

### Set up variables for file and db names.
. variables

### prep

if [ ! -f process ]; then
    echo "process must be run from the git checkout"
    exit 1
fi

# ensure DATA is present for simplicity
mkdir -p DATA

# Nuke and create directory for temporary and output files
rm -rf WORKING
mkdir WORKING

### Download

## Geofabrik Massachusetts

# Thanks to Geofabrik for creating extracts!
# The page for Massachusetts is at:
#   http://download.geofabrik.de/north-america/us/massachusetts.html
if [ ! -f DATA/${MASS_OSM} ]; then
   (cd DATA &&
       if wget http://download.geofabrik.de/north-america/us/massachusetts-latest.osm.pbf; then
	   echo "Downloaded Geofabrik Massachusetts"
       else
	   echo "failed to download Geofabrik Massachusetts"
	   exit 1
       fi)
else
    echo "Geofabrik Massachusetts extract already present"
fi

## MassGIS Statewide Points

# https://docs.digital.mass.gov/dataset/massgis-data-master-address-data
# https://docs.digital.mass.gov/dataset/massgis-data-master-address-data-statewide-address-points-geocoding
# https://www.mass.gov/forms/massgis-request-statewide-address-points-data
if [ -f DATA/${MASSGIS} ]; then
    echo "MassGIS data already present"
else
    echo "Obtain ${MASSGIS} and put it in DATA; see the script for instructions."
    exit 1
fi

### Create and load database

## Drop any existing database.  Create a database and ensure postgis
## is loaded.
# \todo Consider allowing rerunning processing without reloading.
dropdb ${DB}
createdb ${DB}
psql ${DB} -c "CREATE EXTENSION postgis;"
psql ${DB} -c "CREATE EXTENSION hstore;"

## Load the geofabrik extract.
# Note that this clears the database of OSM tables first, but because
# the database is truly empty, that doesn't amtter.

# \todo Create a modified style file so that more address information is included.
osm2pgsql -d ${DB}--hstore -l DATA/${MASS_OSM}

## \todo Load the MassGIS geodatabase.

cd WORKING
unzip ../DATA/${MASSGIS}
# Note the conversion from the source reference system, which is NAD83 state plane, to WGS84.
ogr2ogr -f PGDUMP mass.pgsql MassGIS_Statewide_Address_Points.gdb/a00000009.gdbtable -t_srs EPSG:4326
psql massgis < mass.pgsql > mass.log
